import tskit
import msprime, pyslim
import pandas as pd
import math
import numpy as np
import csv

def calculate_diversity_and_divergence(ts, genome_indicies, time, output_diversities_path, output_divergences_path):
    '''
    Calculate diversity and divergence for given genome indices at a specific time from a tree sequence and outputs them to two csv files.
    
    Parameters:
    ts: tree sequence object
    genome_indicies: list of population indices to sample from
    time: time point to sample
    output_diversities_path: file path to save diversities
    output_divergences_path: file path to save divergences
    '''
    
    #Get all the nodes we are trying to sample from
    pop_samples = []
    for idx in genome_indicies:
        pop_samples.append(ts.samples(population=idx, time=time))

    #Calculate diversity for each population in pop_samples
    diversities = []
    for idx in pop_samples:
        pi = ts.diversity([pop_samples[idx]])
        diversities.append(pi[0])
    diversities = np.array(diversities)

    #Calculate divergence between each pair of populations in pop_samples
    divergences = []
    for i in range(len(genome_indicies)):
        divergences.append([])
        for j in range(len(genome_indicies)):
            if i == j:
                divergences[i].append(0)
            else:
                divergence = ts.divergence([pop_samples[i], pop_samples[j]])
                divergences[i].append(divergence.item())
    
    #write the data
    with open(output_diversities_path, "w", newline="") as f:
        writer = csv.writer(f)
        for item in diversities:
            writer.writerow([item])
        
    with open(output_divergences_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(divergences)



def analyze_tree_sequence():
    '''
    This function analyzes the tree sequence file generated by the SLiM simulation by 
    calculating diversity and divergence statistics before and after recapitation and mutation addition.
    It outputs the results to CSV files.
    '''
    
    # Load the cluster_data CSV file
    cluster_data = pd.read_csv("../data/cluster_data.csv")

    assignments = cluster_data['Genome Assignment']

    total_assignments = int(max(assignments.dropna())) 

    genome_indicies = [-1] * (total_assignments+1)

    for i in range(len(assignments)):
        if math.isnan(assignments[i]) == False:
            index = int(assignments[i])
            if genome_indicies[index] == -1:
                genome_indicies[index] = i

    # Load the tree sequence file
    ts = tskit.load("../out/simTreeSeq.trees")


    diversities = []
    for idx in genome_indicies:
        # Get the sample node for this population
        pop_samples = ts.samples(population=idx)
        #calculate diversity and append to list
        pi = ts.diversity([pop_samples])
        diversities.append(pi[0])
    diversities = np.array(diversities)


    ts = pyslim.recapitate(ts, recombination_rate=1e-8, ancestral_Ne=6700)
    # ts = ts.simplify(samples=genome_indicies)
    next_id = pyslim.next_slim_mutation_id(ts)
    ts = msprime.sim_mutations(
            ts,
            rate=1e-8,
            model=msprime.SLiMMutationModel(type=0, next_id=next_id),
            keep=True,
    )


    calculate_diversity_and_divergence(
        ts, genome_indicies, time=0,
        output_diversities_path="../data/Output_Data/diversities_2023.csv",
        output_divergences_path="../data/Output_Data/divergences_2023.csv")
    
    calculate_diversity_and_divergence(
        ts, genome_indicies, time=8,
        output_diversities_path="../data/Output_Data/diversities_2019.csv",
        output_divergences_path="../data/Output_Data/divergences_2019.csv")
    
    calculate_diversity_and_divergence(
        ts, genome_indicies, time=16,
        output_diversities_path="../data/Output_Data/diversities_2015.csv",
        output_divergences_path="../data/Output_Data/divergences_2015.csv")
        
    